/*************************************************
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * ***********************************************/

package main

import (
	"fmt"
)

func main() {
	var n1 int64 = 1
	var n2 int64 = 2
	var n3 int64 = 3
	sum := n2

	for n3 < 4000000 {
		n1 = n2
		n2 = n3
		n3 = n1 + n2

		if n3%2 == 0 {
			sum += n3
		}

		fmt.Println(sum)
	}
}
